#!/usr/bin/env python
import rospy
import tf
import math
from geometry_msgs.msg import Twist

if __name__ == '__main__':
	rospy.init_node("return_to_origin")
	listener = tf.TransformListener()
	listener.waitForTransform("/base_footprint","/odom",rospy.Time(),rospy.Duration(10.0))

	rospy.loginfo("test")

	vel = rospy.Publisher('/cmd_vel_mux/input/navi',Twist, queue_size = 1)

	rate = rospy.Rate(10.0)

	while not rospy.is_shutdown():
		(trans,rot) = listener.lookupTransform('base_footprint','/odom', rospy.Time(0))
		angular = 4 * math.atan2(trans[1], trans[0])
		#stops working here	
        linear = 0.5 * math.sqrt(trans[0] ** 2 + trans[1] ** 2)
        cmd = Twist()
        cmd.linear.x = 0.5
        cmd.angular.z = rangular
        rospy.loginfo(cmd)
        vel.publish(cmd)

        rospy.loginfo(angular)

        rate.sleep()

